[project]
name = "python-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tuski0", email = "tuski0@naver.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
python-final-project = "python_final_project:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
